//! 33³ RGB lookup tables and the `.cube` interchange format.
//!
//! LUTs are written to the cache as `.cube` rather than kept in memory only:
//! it keeps them inspectable, and a user can load one in RawTherapee or
//! darktable to reproduce a look by hand. Content-addressing means visually
//! similar frames in a burst share a single file.

use crate::develop::DevelopError;

/// Lattice points per axis. 33 is the de-facto standard and what the model
/// was trained at.
pub const LUT_DIM: usize = 33;

/// A 33³ RGB lookup table. Indexed `((b * DIM + g) * DIM + r) * 3`, which is
/// the ordering the `.cube` format iterates in (red fastest).
#[derive(Debug, Clone, PartialEq)]
pub struct Lut33 {
    pub data: Vec<f32>,
}

impl Lut33 {
    pub fn identity() -> Self {
        let mut data = Vec::with_capacity(LUT_DIM * LUT_DIM * LUT_DIM * 3);
        let last = (LUT_DIM - 1) as f32;
        for b in 0..LUT_DIM {
            for g in 0..LUT_DIM {
                for r in 0..LUT_DIM {
                    data.push(r as f32 / last);
                    data.push(g as f32 / last);
                    data.push(b as f32 / last);
                }
            }
        }
        Self { data }
    }

    /// Blend basis LUTs by predictor weights into one image-specific table.
    ///
    /// Weights come straight from a CNN and are unconstrained — they can be
    /// negative or sum above one — so the result is clamped. Returns the
    /// identity on a length mismatch rather than producing a partly-fused table.
    pub fn fuse(basis: &[Lut33], weights: &[f32]) -> Lut33 {
        if basis.is_empty() || basis.len() != weights.len() {
            tracing::warn!(
                basis = basis.len(),
                weights = weights.len(),
                "LUT fuse operand mismatch; falling back to identity"
            );
            return Lut33::identity();
        }
        let mut out = vec![0.0f32; LUT_DIM * LUT_DIM * LUT_DIM * 3];
        for (lut, w) in basis.iter().zip(weights.iter()) {
            if lut.data.len() != out.len() || !w.is_finite() {
                return Lut33::identity();
            }
            for (o, v) in out.iter_mut().zip(lut.data.iter()) {
                *o += w * v;
            }
        }
        for v in out.iter_mut() {
            *v = if v.is_finite() {
                v.clamp(0.0, 1.0)
            } else {
                0.0
            };
        }
        Lut33 { data: out }
    }

    pub fn to_cube(&self) -> String {
        let mut s = String::with_capacity(self.data.len() * 8);
        s.push_str("# Generated by photopipe\n");
        s.push_str("TITLE \"photopipe adaptive look\"\n");
        s.push_str(&format!("LUT_3D_SIZE {LUT_DIM}\n"));
        s.push_str("DOMAIN_MIN 0.0 0.0 0.0\n");
        s.push_str("DOMAIN_MAX 1.0 1.0 1.0\n");
        for rgb in self.data.chunks_exact(3) {
            s.push_str(&format!("{:.6} {:.6} {:.6}\n", rgb[0], rgb[1], rgb[2]));
        }
        s
    }

    pub fn from_cube(text: &str) -> Result<Lut33, DevelopError> {
        let bad = |reason: &str| DevelopError::Render {
            path: std::path::PathBuf::from("<cube>"),
            reason: reason.to_string(),
        };

        let mut data = Vec::with_capacity(LUT_DIM * LUT_DIM * LUT_DIM * 3);
        let mut declared: Option<usize> = None;
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(rest) = line.strip_prefix("LUT_3D_SIZE") {
                declared = rest.trim().parse::<usize>().ok();
                continue;
            }
            if line.starts_with("TITLE") || line.starts_with("DOMAIN") || line.starts_with("LUT_") {
                continue;
            }
            let mut parts = line.split_whitespace();
            let (Some(r), Some(g), Some(b)) = (parts.next(), parts.next(), parts.next()) else {
                return Err(bad("entry line does not hold three values"));
            };
            for v in [r, g, b] {
                data.push(v.parse::<f32>().map_err(|_| bad("non-numeric entry"))?);
            }
        }

        match declared {
            Some(d) if d == LUT_DIM => {}
            Some(d) => return Err(bad(&format!("LUT_3D_SIZE {d}, expected {LUT_DIM}"))),
            None => return Err(bad("missing LUT_3D_SIZE")),
        }
        if data.len() != LUT_DIM * LUT_DIM * LUT_DIM * 3 {
            return Err(bad(&format!(
                "expected {} values, found {}",
                LUT_DIM * LUT_DIM * LUT_DIM * 3,
                data.len()
            )));
        }
        Ok(Lut33 { data })
    }

    /// Content hash, used as the cache filename so visually similar frames
    /// share one `.cube`.
    pub fn content_hash(&self) -> String {
        use std::hash::Hasher;
        let mut h = xxhash_rust::xxh3::Xxh3::new();
        for v in &self.data {
            h.write_i32((v * 100_000.0).round() as i32);
        }
        format!("{:016x}", h.finish())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The identity LUT maps every lattice point to itself.
    #[test]
    fn identity_maps_each_point_to_itself() {
        let lut = Lut33::identity();
        for (i, expected) in [(0usize, 0.0f32), (LUT_DIM - 1, 1.0)] {
            let idx = (i * LUT_DIM * LUT_DIM + i * LUT_DIM + i) * 3;
            assert!((lut.data[idx] - expected).abs() < 1e-6);
            assert!((lut.data[idx + 1] - expected).abs() < 1e-6);
            assert!((lut.data[idx + 2] - expected).abs() < 1e-6);
        }
    }

    /// A .cube round trip is lossless to within the written precision.
    #[test]
    fn cube_round_trips() {
        let lut = Lut33::identity();
        let text = lut.to_cube();
        let back = Lut33::from_cube(&text).expect("parse");
        for (a, b) in lut.data.iter().zip(back.data.iter()) {
            assert!((a - b).abs() < 1e-5, "{a} != {b}");
        }
    }

    /// The emitted .cube declares the size and holds exactly DIM^3 entries,
    /// so RawTherapee and darktable can load it.
    #[test]
    fn cube_header_and_entry_count_are_well_formed() {
        let text = Lut33::identity().to_cube();
        assert!(text.contains("LUT_3D_SIZE 33"), "{text}");
        let entries = text
            .lines()
            .filter(|l| {
                !l.is_empty()
                    && !l.starts_with('#')
                    && !l.starts_with("LUT_")
                    && !l.starts_with("TITLE")
                    && !l.starts_with("DOMAIN")
            })
            .count();
        assert_eq!(entries, LUT_DIM * LUT_DIM * LUT_DIM);
    }

    /// Fusing weighted basis LUTs is a plain linear combination.
    #[test]
    fn fuse_is_a_weighted_sum() {
        let mut a = Lut33::identity();
        a.data.iter_mut().for_each(|v| *v = 0.0);
        let mut b = Lut33::identity();
        b.data.iter_mut().for_each(|v| *v = 1.0);
        let fused = Lut33::fuse(&[a, b], &[0.25, 0.75]);
        assert!((fused.data[0] - 0.75).abs() < 1e-6, "got {}", fused.data[0]);
    }

    /// Fused values must stay in range whatever the predictor emits — weights
    /// from a CNN are unconstrained and can be negative or sum above one.
    #[test]
    fn fuse_clamps_out_of_range_results() {
        let mut hot = Lut33::identity();
        hot.data.iter_mut().for_each(|v| *v = 1.0);
        let fused = Lut33::fuse(&[hot], &[5.0]);
        assert!(fused.data.iter().all(|v| (0.0..=1.0).contains(v)));
    }

    /// A weight/basis length mismatch returns the identity rather than
    /// panicking or producing a partly-fused table.
    #[test]
    fn mismatched_weights_fall_back_to_identity() {
        let fused = Lut33::fuse(&[Lut33::identity()], &[0.5, 0.5]);
        assert_eq!(fused.data, Lut33::identity().data);
    }

    /// Content hashing is what makes LUTs shareable between similar frames.
    #[test]
    fn content_hash_is_stable_and_sensitive() {
        let a = Lut33::identity();
        assert_eq!(a.content_hash(), Lut33::identity().content_hash());
        let mut b = Lut33::identity();
        b.data[0] += 0.5;
        assert_ne!(a.content_hash(), b.content_hash());
    }

    /// Malformed input is an error, not a panic.
    #[test]
    fn malformed_cube_is_an_error() {
        assert!(Lut33::from_cube("").is_err());
        assert!(Lut33::from_cube("LUT_3D_SIZE 33\n0.0 0.0").is_err());
        assert!(
            Lut33::from_cube("LUT_3D_SIZE 17\n").is_err(),
            "wrong size must be rejected"
        );
    }
}
