//! `EditRecipe` → RawTherapee processing profile.
//!
//! Emits ONLY technical corrections. The look is applied afterwards, in Rust,
//! to the 16-bit TIFF (spec §4). Nothing here may touch film simulation, tone
//! curves, or saturation — `base.pp3` owns those, and overriding them would
//! change the input distribution the look model was trained on.
//!
//! Key names come from `docs/design/pp3-keys.md`, established by having
//! `rawtherapee-cli -O` emit a complete neutral profile. RawTherapee silently
//! ignores unknown keys, so drift here is invisible at runtime and only the
//! golden test catches it.

use crate::develop::decide::EditRecipe;

/// The version-controlled neutral baseline, applied before the per-photo
/// profile. Embedded so the binary carries no external file dependency.
pub const BASE_PP3: &str = include_str!("../../assets/base.pp3");

/// Render `recipe` as a `.pp3` to stack on top of `BASE_PP3`.
pub fn emit_pp3(recipe: &EditRecipe) -> String {
    let mut s = String::with_capacity(1024);

    s.push_str("# Generated by photopipe. Stacked on base.pp3; do not edit by hand.\n");

    // ── exposure ──
    s.push_str("\n[Exposure]\n");
    // Auto must be false or RawTherapee overrides our compensation.
    s.push_str("Auto=false\n");
    s.push_str(&format!("Compensation={}\n", f3(recipe.exposure_ev)));

    // ── highlight reconstruction ──
    s.push_str("\n[HLRecovery]\n");
    if recipe.highlight_recovery > 0.0 {
        s.push_str("Enabled=true\n");
        // The method escalates with severity: blending is gentle and safe for
        // mild clipping; colour propagation reconstructs hue from neighbouring
        // unclipped channels and is what heavy clipping needs.
        let method = if recipe.highlight_recovery < 0.5 {
            "Blend"
        } else {
            "Coloropp"
        };
        s.push_str(&format!("Method={method}\n"));
    } else {
        s.push_str("Enabled=false\n");
    }

    // ── shadows ──
    s.push_str("\n[Shadows & Highlights]\n");
    if recipe.shadow_lift > 0.0 {
        s.push_str("Enabled=true\n");
        s.push_str(&format!("Shadows={}\n", pct(recipe.shadow_lift)));
        s.push_str("Highlights=0\n");
    } else {
        s.push_str("Enabled=false\n");
    }

    // ── white balance ──
    // Setting=Camera applies the camera's own as-shot coefficients exactly.
    //
    // We deliberately do NOT convert those coefficients into RawTherapee's
    // Temperature/Green parameterisation. An earlier revision did, and the
    // conversion was wrong twice over: the temperature relation was inverted
    // (tungsten light produced 8214 K, daylight 3713 K) and Green landed
    // systematically near 0.5 against its 1.0 neutral, casting every frame
    // magenta. RawTherapee derives its own multipliers from the camera profile,
    // so asking it to use the camera WB is both exact and simpler than
    // restating that WB in a foreign parameterisation. `EditRecipe` carries no
    // white-balance field at all (see `crate::develop::decide`), so nothing is
    // read from `recipe` here.
    //
    // The PCA illuminant estimate is still measured and stored in `raw_stats`;
    // acting on it needs a verifiable conversion and is deferred.
    s.push_str("\n[White Balance]\n");
    s.push_str("Enabled=true\n");
    s.push_str("Setting=Camera\n");

    // ── denoise ──
    s.push_str("\n[Directional Pyramid Denoising]\n");
    if recipe.denoise_luma > 0.0 || recipe.denoise_chroma > 0.0 {
        s.push_str("Enabled=true\n");
        // TRAP: a single Chroma slider requires Method=Lab AND CMethod=MAN.
        // Under CMethod=AUT — which several bundled profiles use — Chroma is
        // ignored. See docs/design/pp3-keys.md.
        s.push_str("Method=Lab\n");
        s.push_str("CMethod=MAN\n");
        s.push_str(&format!("Luma={}\n", pct(recipe.denoise_luma)));
        s.push_str(&format!("Chroma={}\n", pct(recipe.denoise_chroma)));
    } else {
        s.push_str("Enabled=false\n");
    }

    // ── capture sharpening ──
    s.push_str("\n[PostDemosaicSharpening]\n");
    if recipe.sharpen_amount > 0.0 {
        s.push_str("Enabled=true\n");
        // TRAP: AutoContrast and AutoRadius both default to true, and each
        // overrides the manual value below it. See docs/design/pp3-keys.md.
        s.push_str("AutoContrast=false\n");
        s.push_str("AutoRadius=false\n");
        s.push_str(&format!("Contrast={}\n", pct(recipe.sharpen_amount)));
        s.push_str("DeconvRadius=0.750\n");
    } else {
        s.push_str("Enabled=false\n");
    }

    // ── lens correction ──
    // Omitted entirely when off, so base.pp3's own setting stands.
    if recipe.lens_correct {
        s.push_str("\n[LensProfile]\n");
        s.push_str("LcMode=lfauto\n");
        s.push_str("UseDistortion=true\n");
        s.push_str("UseVignette=true\n");
        s.push_str("UseCA=false\n");
    }

    s
}

/// Three decimal places, always `.`, never scientific notation. RawTherapee's
/// parser accepts neither locale commas nor exponents.
fn f3(v: f32) -> String {
    format!("{:.3}", if v.is_finite() { v } else { 0.0 })
}

/// A 0..1 recipe field as RawTherapee's 0..100 integer scale.
fn pct(v: f32) -> i32 {
    (v.clamp(0.0, 1.0) * 100.0).round() as i32
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::develop::decide::EditRecipe;

    fn fixed_recipe() -> EditRecipe {
        EditRecipe {
            exposure_ev: 0.75,
            highlight_recovery: 0.6,
            shadow_lift: 0.4,
            denoise_luma: 0.3,
            denoise_chroma: 0.36,
            sharpen_amount: 0.5,
            lens_correct: true,
        }
    }

    /// Golden-file test: a fixed recipe produces byte-exact .pp3 text.
    /// This is what catches accidental key drift.
    #[test]
    fn fixed_recipe_matches_golden_file() {
        let got = emit_pp3(&fixed_recipe());
        let want = include_str!("../../tests/fixtures/golden.pp3");
        assert_eq!(
            got, want,
            "\n--- emitted ---\n{got}\n--- expected ---\n{want}"
        );
    }

    /// Percent-scaled fields map from 0..1 onto RawTherapee's 0..100.
    #[test]
    fn unit_fields_scale_to_percent() {
        let out = emit_pp3(&fixed_recipe());
        assert!(
            out.contains("Luma=30"),
            "denoise_luma 0.3 should emit 30:\n{out}"
        );
        assert!(
            out.contains("Chroma=36"),
            "denoise_chroma 0.36 should emit 36:\n{out}"
        );
    }

    /// The silent no-op traps from docs/design/pp3-keys.md. Each of these
    /// keys defaults to a value that makes a neighbouring key we DO set be
    /// ignored, with no warning from RawTherapee.
    ///
    /// White balance is the one exception, and deliberately so: `EditRecipe`
    /// has no WB fields at all (see `crate::develop::decide`) because v1 uses
    /// the camera's own as-shot coefficients. `Setting=Camera` is therefore
    /// the *wanted* value here, emitted explicitly rather than left to
    /// RawTherapee's default so a future default change cannot silently move
    /// it to something else.
    #[test]
    fn silent_no_op_traps_are_defused() {
        let out = emit_pp3(&fixed_recipe());
        assert!(
            out.contains("Setting=Camera"),
            "v1 uses the camera's own WB:\n{out}"
        );
        assert!(
            out.contains("AutoContrast=false"),
            "Contrast would be ignored:\n{out}"
        );
        assert!(
            out.contains("AutoRadius=false"),
            "DeconvRadius would be ignored:\n{out}"
        );
        assert!(
            out.contains("CMethod=MAN"),
            "Chroma would be ignored:\n{out}"
        );
    }

    /// Zeroed corrections emit disabled tools, not enabled ones set to zero —
    /// an enabled no-op tool still costs render time.
    #[test]
    fn zero_strength_disables_the_tool() {
        let mut r = fixed_recipe();
        r.highlight_recovery = 0.0;
        r.denoise_luma = 0.0;
        r.denoise_chroma = 0.0;
        r.shadow_lift = 0.0;
        let out = emit_pp3(&r);
        assert!(out.contains("[HLRecovery]\nEnabled=false"), "{out}");
        assert!(
            out.contains("[Directional Pyramid Denoising]\nEnabled=false"),
            "{out}"
        );
    }

    /// Lens correction off must not emit a LensProfile section at all, so the
    /// base profile's own setting is left untouched.
    #[test]
    fn lens_correction_off_omits_the_section() {
        let mut r = fixed_recipe();
        r.lens_correct = false;
        let out = emit_pp3(&r);
        assert!(!out.contains("[LensProfile]"), "{out}");
    }

    /// Floats must render with a fixed decimal count and a `.` separator —
    /// never locale-dependent, and never scientific notation, which
    /// RawTherapee cannot parse.
    ///
    /// Checked against the specific `Compensation=` line rather than the
    /// whole document: a whole-document `!contains('e')` check is always
    /// false here regardless of number formatting, because words like
    /// `Enabled` and `true` contain the letter `e`.
    #[test]
    fn floats_are_formatted_deterministically() {
        let mut r = fixed_recipe();
        r.exposure_ev = 0.000_012_5;
        let out = emit_pp3(&r);
        let line = out
            .lines()
            .find(|l| l.starts_with("Compensation="))
            .expect("Compensation line present");
        assert_eq!(line, "Compensation=0.000", "{out}");
        let value = line.trim_start_matches("Compensation=");
        assert!(
            !value.contains('e') && !value.contains('E'),
            "scientific notation leaked: {line}"
        );
    }

    /// Every emitted line is `key=value` under a section header. A stray line
    /// makes RawTherapee reject the whole profile.
    #[test]
    fn output_is_well_formed_ini() {
        let out = emit_pp3(&fixed_recipe());
        let mut seen_section = false;
        for line in out.lines() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if line.starts_with('[') {
                assert!(line.ends_with(']'), "malformed section: {line}");
                seen_section = true;
                continue;
            }
            assert!(seen_section, "key before any section: {line}");
            assert!(line.contains('='), "not a key=value line: {line}");
        }
    }
}
